### ISSUE TITLE
Encountered (node:4657) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE] after git was initialised

### ISSUE THREAD

**Issue by iRNano** [kvssankar/npmp3#3]
Steps:
1) npm i -g create-ultimate-mern-app
2) cd projects
3) create-ultimate-mern-app mymernapp
4) Check logs for more info:

 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | ETA: 0s | 0/300
Createing Mern app for you..Hold your horses just for 5 minutes

Creating a new React app in /Users/adrianvaldepenas/Documents/projects/mymernapp/client.

Installing packages. This might take a couple of minutes.
 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | ETA: 456s | 1/300Installing react, react-dom, and react-scripts with cra-template...

yarn add v1.22.4
[1/4] Resolving packages...
 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1% | ETA: 449s | 3/300[2/4] Fetching packages...
 █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1% | ETA: 447s | 4/300[3/4] Linking dependencies...
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5
 ███░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 6% | ETA: 423s | 19/300[4/4] Building fresh packages...
 ███░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 8% | ETA: 412s | 26/300success Saved lockfile.
success Saved 15 new dependencies.
info Direct dependencies
├─ cra-template@1.0.3
├─ react-dom@16.13.1
├─ react-scripts@3.4.1
└─ react@16.13.1
info All dependencies
├─ @babel/helper-member-expression-to-functions@7.10.3
├─ @babel/plugin-syntax-typescript@7.10.1
├─ @babel/plugin-transform-flow-strip-types@7.9.0
├─ @babel/plugin-transform-runtime@7.9.0
├─ @babel/plugin-transform-typescript@7.10.3
├─ @babel/preset-typescript@7.9.0
├─ babel-preset-react-app@9.1.2
├─ cra-template@1.0.3
├─ eslint-config-react-app@5.2.1
├─ react-dev-utils@10.2.1
├─ react-dom@16.13.1
├─ react-error-overlay@6.0.7
├─ react-scripts@3.4.1
├─ react@16.13.1
└─ scheduler@0.19.1
Done in 38.06s.
 ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 9% | ETA: 411s | 27/300
Initialized a git repository.

Installing template dependencies using yarnpkg...
 ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 9% | ETA: 409s | 28/300yarn add v1.22.4
[1/4] Resolving packages...
 ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 10% | ETA: 406s | 30/300warning @testing-library/react > @types/testing-library__react > @types/testing-library__dom@7.5.0: This is a stu
 ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 10% | ETA: 403s | 32/300[2/4] Fetching packages...
 ████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 11% | ETA: 402s | 33/300[3/4] Linking dependencies...
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5
warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
 █████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 13% | ETA: 389s | 41/300[4/4] Building fresh packages...
success Saved lockfile.
 ██████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 14% | ETA: 388s | 42/300success Saved 21 new dependencies.
info Direct dependencies
├─ @testing-library/jest-dom@4.2.4
├─ @testing-library/react@9.5.0
├─ @testing-library/user-event@7.2.1
├─ react-dom@16.13.1
└─ react@16.13.1
info All dependencies
├─ @babel/runtime-corejs3@7.10.3
├─ @sheerun/mutationobserver-shim@0.3.3
├─ @testing-library/dom@6.16.0
├─ @testing-library/jest-dom@4.2.4
├─ @testing-library/react@9.5.0
├─ @testing-library/user-event@7.2.1
├─ @types/prop-types@15.7.3
├─ @types/react-dom@16.9.8
├─ @types/react@16.9.41
├─ @types/testing-library__dom@7.5.0
├─ @types/testing-library__react@9.1.3
├─ aria-query@4.2.2
├─ css.escape@1.5.1
├─ csstype@2.6.10
├─ dom-accessibility-api@0.3.0
├─ min-indent@1.0.1
├─ react-dom@16.13.1
├─ react@16.13.1
├─ redent@3.0.0
├─ strip-indent@3.0.0
└─ wait-for-expect@3.0.2
Done in 21.10s.
Removing template package using yarnpkg...

yarn remove v1.22.4
[1/2] Removing module cra-template...
[2/2] Regenerating lockfile and installing missing dependencies...
 ██████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 15% | ETA: 384s | 45/300warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5
 ████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 19% | ETA: 364s | 58/300success Uninstalled packages.
Done in 23.78s.

Created git commit.

Success! Created client at /Users/adrianvaldepenas/Documents/projects/mymernapp/client
Inside that directory, you can run several commands:

  yarn start
    Starts the development server.

  yarn build
    Bundles the app into static files for production.

  yarn test
    Starts the test runner.

  yarn eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd client
  yarn start

Happy hacking!

Created react app for you

Wrote to /Users/adrianvaldepenas/Documents/projects/mymernapp/package.json:

{
  "name": "mymernapp",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

package.json created..

Initialized empty Git repository in /Users/adrianvaldepenas/Documents/projects/mymernapp/.git/

git initialised

(node:4657) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFile (fs.js:1356:5)
    at /usr/local/lib/node_modules/create-ultimate-mern-app/index.js:310:12
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/create-ultimate-mern-app/index.js:309:21
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/create-ultimate-mern-app/index.js:308:22
    at new Promise (<anonymous>)
    at createGitFile (/usr/local/lib/node_modules/create-ultimate-mern-app/index.js:306:10)
    at run (/usr/local/lib/node_modules/create-ultimate-mern-app/index.js:17:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4657) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:4657) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
node --trace-warnings

**Comment by iRNano** [comment]
After retrying, error was still encountered.

(node:5398) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received undefined
    at Object.writeFile (fs.js:1356:5)
    at /usr/local/lib/node_modules/create-ultimate-mern-app/index.js:310:12
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/create-ultimate-mern-app/index.js:309:21
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/create-ultimate-mern-app/index.js:308:22
    at new Promise (<anonymous>)
    at createGitFile (/usr/local/lib/node_modules/create-ultimate-mern-app/index.js:306:10)
    at run (/usr/local/lib/node_modules/create-ultimate-mern-app/index.js:17:11)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5398) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5398) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by kvssankar** [comment]
These r the possible checks you can do
1. Try uninstalling and  npm i -g create-ultimate-mern-app and try again
2. If u have recently changed GitHub password reinitialize it in your command prompt
If the issue still persist please create an issue in GitHub

**Comment by kvssankar** [comment]
Sorry for the inconvenience your issue has been resolved please update the package using
npm i -g create-ultimate-mern-app

**Comment by iRNano** [comment]
Hi @kvssankar , first issue was resolve but encountered another one. 

Error was encountered while creating server side.. Please check logs for more info:

create-ultimate-mern-app mymernapp3
 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | ETA: 0s | 0/300
Createing Mern app for you..Hold your horses just for 5 minutes


Creating a new React app in /Users/adrianvaldepenas/Documents/projects/mymernapp3/client.

 ░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 0% | ETA: 456s | 1/300Installing packages. This might take a couple of minutes.
Installing react, react-dom, and react-scripts with cra-template...

yarn add v1.22.4
[1/4] Resolving packages...
 █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 1% | ETA: 447s | 4/300[2/4] Fetching packages...
 █░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 2% | ETA: 443s | 6/300[3/4] Linking dependencies...
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5
 █████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 12% | ETA: 396s | 37/300[4/4] Building fresh packages...
 ██████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 16% | ETA: 379s | 48/300success Saved lockfile.
 ███████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 16% | ETA: 378s | 49/300success Saved 15 new dependencies.
info Direct dependencies
├─ cra-template@1.0.3
├─ react-dom@16.13.1
├─ react-scripts@3.4.1
└─ react@16.13.1
info All dependencies
├─ @babel/helper-member-expression-to-functions@7.10.3
├─ @babel/plugin-syntax-typescript@7.10.1
├─ @babel/plugin-transform-flow-strip-types@7.9.0
├─ @babel/plugin-transform-runtime@7.9.0
├─ @babel/plugin-transform-typescript@7.10.3
├─ @babel/preset-typescript@7.9.0
├─ babel-preset-react-app@9.1.2
├─ cra-template@1.0.3
├─ eslint-config-react-app@5.2.1
├─ react-dev-utils@10.2.1
├─ react-dom@16.13.1
├─ react-error-overlay@6.0.7
├─ react-scripts@3.4.1
├─ react@16.13.1
└─ scheduler@0.19.1
Done in 71.64s.
 ███████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 16% | ETA: 376s | 50/300
Initialized a git repository.

Installing template dependencies using yarnpkg...
yarn add v1.22.4
 ███████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 17% | ETA: 375s | 51/300[1/4] Resolving packages...
 ███████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 17% | ETA: 372s | 53/300warning @testing-library/react > @types/testing-library__react > @types/testing-library__dom@7.5.0: This is a stu
 ███████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 18% | ETA: 370s | 54/300[2/4] Fetching packages...
 ███████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 18% | ETA: 367s | 56/300[3/4] Linking dependencies...
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5
warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
 █████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 22% | ETA: 352s | 66/300[4/4] Building fresh packages...
 █████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 22% | ETA: 350s | 67/300success Saved lockfile.
success Saved 21 new dependencies.
info Direct dependencies
├─ @testing-library/jest-dom@4.2.4
├─ @testing-library/react@9.5.0
├─ @testing-library/user-event@7.2.1
├─ react-dom@16.13.1
└─ react@16.13.1
info All dependencies
├─ @babel/runtime-corejs3@7.10.3
├─ @sheerun/mutationobserver-shim@0.3.3
├─ @testing-library/dom@6.16.0
├─ @testing-library/jest-dom@4.2.4
├─ @testing-library/react@9.5.0
├─ @testing-library/user-event@7.2.1
├─ @types/prop-types@15.7.3
├─ @types/react-dom@16.9.8
├─ @types/react@16.9.41
├─ @types/testing-library__dom@7.5.0
├─ @types/testing-library__react@9.1.3
├─ aria-query@4.2.2
├─ css.escape@1.5.1
├─ csstype@2.6.10
├─ dom-accessibility-api@0.3.0
├─ min-indent@1.0.1
├─ react-dom@16.13.1
├─ react@16.13.1
├─ redent@3.0.0
├─ strip-indent@3.0.0
└─ wait-for-expect@3.0.2
Done in 25.13s.
Removing template package using yarnpkg...

 █████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 22% | ETA: 349s | 68/300yarn remove v1.22.4
[1/2] Removing module cra-template...
[2/2] Regenerating lockfile and installing missing dependencies...
 ██████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 24% | ETA: 343s | 72/300warning " > @testing-library/user-event@7.2.1" has unmet peer dependency "@testing-library/dom@>=5".
warning "react-scripts > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5
 ████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░ 30% | ETA: 314s | 91/300success Uninstalled packages.
Done in 34.75s.

Created git commit.

Success! Created client at /Users/adrianvaldepenas/Documents/projects/mymernapp3/client
Inside that directory, you can run several commands:

  yarn start
    Starts the development server.

  yarn build
    Bundles the app into static files for production.

  yarn test
    Starts the test runner.

  yarn eject
    Removes this tool and copies build dependencies, configuration files
    and scripts into the app directory. If you do this, you can’t go back!

We suggest that you begin by typing:

  cd client
  yarn start

Happy hacking!

Created react app for you

Wrote to /Users/adrianvaldepenas/Documents/projects/mymernapp3/package.json:

{
  "name": "mymernapp3",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}



package.json created..

Initialized empty Git repository in /Users/adrianvaldepenas/Documents/projects/mymernapp3/.git/

git initialised


Installing server pages express mongoose

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN mymernapp3@1.0.0 No description
npm WARN mymernapp3@1.0.0 No repository field.

+ express@4.17.1
+ concurrently@5.2.0
+ config@3.3.1
+ mongoose@5.9.20
added 133 packages from 97 contributors and audited 133 packages in 19.313s

4 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities


Finished installing packages


Installing client packages

npm WARN deprecated popper.js@1.16.1: You can find the new Popper v2 at @popperjs/core, this package is dedicated to the legacy v1
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated fsevents@1.2.12: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated mkdirp@0.5.3: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN deprecated left-pad@1.3.0: use String.prototype.padStart()
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
npm WARN rm not removing /Users/adrianvaldepenas/Documents/projects/mymernapp3/client/node_modules/.bin/jest as it wasn't installed by /Users/adrianvaldepenas/Documents/projects/mymernapp3/client/node_modules/jest
npm WARN rm not removing /Users/adrianvaldepenas/Documents/projects/mymernapp3/client/node_modules/.bin/rimraf as it wasn't installed by /Users/adrianvaldepenas/Documents/projects/mymernapp3/client/node_modules/rimraf
npm WARN rm not removing /Users/adrianvaldepenas/Documents/projects/mymernapp3/client/node_modules/.bin/semver as it wasn't installed by /Users/adrianvaldepenas/Documents/projects/mymernapp3/client/node_modules/semver
npm WARN rm not removing /Users/adrianvaldepenas/Documents/projects/mymernapp3/client/node_modules/.bin/mkdirp as it wasn't installed by /Users/adrianvaldepenas/Documents/projects/mymernapp3/client/node_modules/mkdirp
npm WARN rm not removing /Users/adrianvaldepenas/Documents/projects/mymernapp3/client/node_modules/.bin/json5 as it wasn't installed by /Users/adrianvaldepenas/Documents/projects/mymernapp3/client/node_modules/json5

> fsevents@1.2.12 install /Users/adrianvaldepenas/Documents/projects/mymernapp3/client/node_modules/fsevents
> node-gyp rebuild

  SOLINK_MODULE(target) Release/.node
  CXX(target) Release/obj.target/fse/fsevents.o
  SOLINK_MODULE(target) Release/fse.node
ld: warning: text-based stub file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation.tbd and library file /System/Library/Frameworks//CoreFoundation.framework/CoreFoundation are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CoreServices.framework/CoreServices.tbd and library file /System/Library/Frameworks//CoreServices.framework/CoreServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork.tbd and library file /System/Library/Frameworks//CFNetwork.framework/Versions/A/CFNetwork are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/OSServices.framework/Versions/A/OSServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/LaunchServices.framework/Versions/A/LaunchServices are out of sync. Falling back to library file for linking.
ld: warning: text-based stub file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList.tbd and library file /System/Library/Frameworks/CoreServices.framework/Versions/A/Frameworks/SharedFileList.framework/Versions/A/SharedFileList are out of sync. Falling back to library file for linking.

> core-js@2.6.11 postinstall /Users/adrianvaldepenas/Documents/projects/mymernapp3/client/node_modules/babel-runtime/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)


> core-js@3.6.5 postinstall /Users/adrianvaldepenas/Documents/projects/mymernapp3/client/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"


> core-js-pure@3.6.5 postinstall /Users/adrianvaldepenas/Documents/projects/mymernapp3/client/node_modules/core-js-pure
> node -e "try{require('./postinstall')}catch(e){}"

npm notice created a lockfile as package-lock.json. You should commit this file.
npm WARN notsup Unsupported engine for watchpack-chokidar2@2.0.0: wanted: {"node":"<8.10.0"} (current: {"node":"14.4.0","npm":"6.14.4"})
npm WARN notsup Not compatible with your version of node/npm: watchpack-chokidar2@2.0.0
npm WARN bootstrap@4.5.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.2 requires a peer of node-sass@^4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.2 requires a peer of sass@^1.3.0 but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@8.0.2 requires a peer of fibers@>= 3.1.0 but none is installed. You must install peer dependencies yourself.
npm WARN tsutils@3.17.1 requires a peer of typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta but none is installed. You must install peer dependencies yourself.

+ redux-thunk@2.3.0
+ redux@4.0.5
+ react-redux@7.2.0
+ axios@0.19.2
+ react-router-dom@5.2.0
+ bootstrap@4.5.0
+ reactstrap@8.5.1
added 485 packages from 396 contributors, removed 144 packages, updated 1405 packages and audited 1962 packages in 215.45s

65 packages are looking for funding
  run `npm fund` for details

found 1 low severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

Finished installing packages


creating server side...


Finished installing packages

(node:5780) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "data" argument must be of type string or an instance of Buffer, TypedArray, or DataView. Received an instance of Object
    at Object.writeFile (fs.js:1356:5)
    at /usr/local/lib/node_modules/create-ultimate-mern-app/index.js:195:14
    at new Promise (<anonymous>)
    at /usr/local/lib/node_modules/create-ultimate-mern-app/index.js:194:23
    at Array.forEach (<anonymous>)
    at /usr/local/lib/node_modules/create-ultimate-mern-app/index.js:193:27
    at new Promise (<anonymous>)
    at createConfigFile (/usr/local/lib/node_modules/create-ultimate-mern-app/index.js:191:12)
    at run (/usr/local/lib/node_modules/create-ultimate-mern-app/index.js:22:11)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:5780) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 2)
(node:5780) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
